// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "it-stone-server/models"
)

// CreateCardCreatedCode is the HTTP code returned for type CreateCardCreated
const CreateCardCreatedCode int = 201

/*CreateCardCreated Created

swagger:response createCardCreated
*/
type CreateCardCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CreatedEntity `json:"body,omitempty"`
}

// NewCreateCardCreated creates CreateCardCreated with default headers values
func NewCreateCardCreated() *CreateCardCreated {

	return &CreateCardCreated{}
}

// WithPayload adds the payload to the create card created response
func (o *CreateCardCreated) WithPayload(payload *models.CreatedEntity) *CreateCardCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create card created response
func (o *CreateCardCreated) SetPayload(payload *models.CreatedEntity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCardCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateCardDefault Error

swagger:response createCardDefault
*/
type CreateCardDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateCardDefault creates CreateCardDefault with default headers values
func NewCreateCardDefault(code int) *CreateCardDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateCardDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create card default response
func (o *CreateCardDefault) WithStatusCode(code int) *CreateCardDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create card default response
func (o *CreateCardDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create card default response
func (o *CreateCardDefault) WithPayload(payload *models.Error) *CreateCardDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create card default response
func (o *CreateCardDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCardDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
