// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "it-stone-server/models"
)

// CreateCardHandlerFunc turns a function with the right signature into a create card handler
type CreateCardHandlerFunc func(CreateCardParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCardHandlerFunc) Handle(params CreateCardParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateCardHandler interface for that can handle valid create card params
type CreateCardHandler interface {
	Handle(CreateCardParams, *models.Principal) middleware.Responder
}

// NewCreateCard creates a new http.Handler for the create card operation
func NewCreateCard(ctx *middleware.Context, handler CreateCardHandler) *CreateCard {
	return &CreateCard{Context: ctx, Handler: handler}
}

/*CreateCard swagger:route POST /v0/cards card createCard

Create a new card

*/
type CreateCard struct {
	Context *middleware.Context
	Handler CreateCardHandler
}

func (o *CreateCard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateCardParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
