// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "it-stone-server/models"
)

// DeleteCardNoContentCode is the HTTP code returned for type DeleteCardNoContent
const DeleteCardNoContentCode int = 204

/*DeleteCardNoContent The card has been deleted

swagger:response deleteCardNoContent
*/
type DeleteCardNoContent struct {
}

// NewDeleteCardNoContent creates DeleteCardNoContent with default headers values
func NewDeleteCardNoContent() *DeleteCardNoContent {

	return &DeleteCardNoContent{}
}

// WriteResponse to the client
func (o *DeleteCardNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteCardDefault Error

swagger:response deleteCardDefault
*/
type DeleteCardDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteCardDefault creates DeleteCardDefault with default headers values
func NewDeleteCardDefault(code int) *DeleteCardDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteCardDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete card default response
func (o *DeleteCardDefault) WithStatusCode(code int) *DeleteCardDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete card default response
func (o *DeleteCardDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete card default response
func (o *DeleteCardDefault) WithPayload(payload *models.Error) *DeleteCardDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete card default response
func (o *DeleteCardDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCardDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
