// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "it-stone-server/models"
)

// GetCardsHandlerFunc turns a function with the right signature into a get cards handler
type GetCardsHandlerFunc func(GetCardsParams, *models.Token) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCardsHandlerFunc) Handle(params GetCardsParams, principal *models.Token) middleware.Responder {
	return fn(params, principal)
}

// GetCardsHandler interface for that can handle valid get cards params
type GetCardsHandler interface {
	Handle(GetCardsParams, *models.Token) middleware.Responder
}

// NewGetCards creates a new http.Handler for the get cards operation
func NewGetCards(ctx *middleware.Context, handler GetCardsHandler) *GetCards {
	return &GetCards{Context: ctx, Handler: handler}
}

/*GetCards swagger:route GET /v0/cards card getCards

Receiving all cards

*/
type GetCards struct {
	Context *middleware.Context
	Handler GetCardsHandler
}

func (o *GetCards) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCardsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Token
	if uprinc != nil {
		principal = uprinc.(*models.Token) // this is really a models.Token, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
