// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "it-stone-server/models"
)

// UpdateCardHandlerFunc turns a function with the right signature into a update card handler
type UpdateCardHandlerFunc func(UpdateCardParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCardHandlerFunc) Handle(params UpdateCardParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateCardHandler interface for that can handle valid update card params
type UpdateCardHandler interface {
	Handle(UpdateCardParams, *models.Principal) middleware.Responder
}

// NewUpdateCard creates a new http.Handler for the update card operation
func NewUpdateCard(ctx *middleware.Context, handler UpdateCardHandler) *UpdateCard {
	return &UpdateCard{Context: ctx, Handler: handler}
}

/*UpdateCard swagger:route POST /v0/cards/{id} card updateCard

Update one card by ID

*/
type UpdateCard struct {
	Context *middleware.Context
	Handler UpdateCardHandler
}

func (o *UpdateCard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateCardParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
