// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateCardHandlerFunc turns a function with the right signature into a update card handler
type UpdateCardHandlerFunc func(UpdateCardParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCardHandlerFunc) Handle(params UpdateCardParams) middleware.Responder {
	return fn(params)
}

// UpdateCardHandler interface for that can handle valid update card params
type UpdateCardHandler interface {
	Handle(UpdateCardParams) middleware.Responder
}

// NewUpdateCard creates a new http.Handler for the update card operation
func NewUpdateCard(ctx *middleware.Context, handler UpdateCardHandler) *UpdateCard {
	return &UpdateCard{Context: ctx, Handler: handler}
}

/*UpdateCard swagger:route POST /v0/cards/{id} card updateCard

UpdateCard update card API

*/
type UpdateCard struct {
	Context *middleware.Context
	Handler UpdateCardHandler
}

func (o *UpdateCard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateCardParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
