// Code generated by go-swagger; DO NOT EDIT.

package registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "it-stone-server/models"
)

// RegistrationOKCode is the HTTP code returned for type RegistrationOK
const RegistrationOKCode int = 200

/*RegistrationOK Registration successful

swagger:response registrationOK
*/
type RegistrationOK struct {
}

// NewRegistrationOK creates RegistrationOK with default headers values
func NewRegistrationOK() *RegistrationOK {

	return &RegistrationOK{}
}

// WriteResponse to the client
func (o *RegistrationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*RegistrationDefault Internal server error

swagger:response registrationDefault
*/
type RegistrationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegistrationDefault creates RegistrationDefault with default headers values
func NewRegistrationDefault(code int) *RegistrationDefault {
	if code <= 0 {
		code = 500
	}

	return &RegistrationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the registration default response
func (o *RegistrationDefault) WithStatusCode(code int) *RegistrationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the registration default response
func (o *RegistrationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the registration default response
func (o *RegistrationDefault) WithPayload(payload *models.Error) *RegistrationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the registration default response
func (o *RegistrationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegistrationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
