// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi IT-Stone Server
Description for API IT-Stone


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 0.0.2

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
