// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Description for API Server",
    "title": "IT-Stone Server",
    "version": "0.0.2"
  },
  "basePath": "/api",
  "paths": {
    "/v0/auth/callback": {
      "get": {
        "security": [],
        "summary": "Return access_token and user",
        "operationId": "callback",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "$ref": "#/definitions/UserToken"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/cards": {
      "get": {
        "tags": [
          "card"
        ],
        "summary": "Receiving all cards",
        "operationId": "getCards",
        "responses": {
          "200": {
            "description": "Cards array",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Card"
              }
            }
          },
          "default": {
            "description": "generic Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "card"
        ],
        "summary": "Create a new card",
        "operationId": "createCard",
        "parameters": [
          {
            "name": "card",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/CreatedEntity"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/cards/{id}": {
      "get": {
        "tags": [
          "card"
        ],
        "summary": "Receiving one card by ID",
        "operationId": "getCard",
        "responses": {
          "200": {
            "description": "Return a card with the specified ID",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          },
          "404": {
            "description": "The card with the specified ID was not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "generic Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "card"
        ],
        "summary": "Update one card by ID",
        "operationId": "updateCard",
        "parameters": [
          {
            "name": "card",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The card has been updated",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "card"
        ],
        "summary": "Delete one card by ID",
        "operationId": "deleteCard",
        "responses": {
          "204": {
            "description": "The card has been deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/v0/login": {
      "get": {
        "security": [],
        "tags": [
          "login"
        ],
        "summary": "Login by using Google client OAuth 2.0.",
        "operationId": "login",
        "responses": {
          "200": {
            "description": "Login successful.",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/users": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Receiving all users",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "Receiving all users",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "default": {
            "description": "generic Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/users/{id}": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Receiving the user by ID",
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "404": {
            "description": "The user not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Update the user by ID",
        "operationId": "updateUser",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update success",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "404": {
            "description": "The user not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Delete the user by ID",
        "operationId": "deleteUser",
        "responses": {
          "200": {
            "description": "Delete success"
          },
          "404": {
            "description": "The user not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Card": {
      "type": "object",
      "properties": {
        "class": {
          "type": "string"
        },
        "damage": {
          "type": "number"
        },
        "effects": {
          "type": "object"
        },
        "hp": {
          "type": "number"
        },
        "id": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "mana_cost": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "surname": {
          "type": "string"
        }
      }
    },
    "CreatedEntity": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "description": "The email of the User.",
          "type": "string"
        },
        "firstName": {
          "description": "First name of the User.",
          "type": "string"
        },
        "lastName": {
          "description": "Last name of the User.",
          "type": "string"
        },
        "totalGames": {
          "description": "Count of all games of the User.",
          "type": "integer"
        },
        "userID": {
          "description": "The ID of the User.",
          "type": "string"
        },
        "userName": {
          "description": "The user name.",
          "type": "string"
        },
        "winGames": {
          "description": "Count of all games where the User has won.",
          "type": "integer"
        }
      }
    },
    "UserToken": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    }
  },
  "securityDefinitions": {
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
      "scopes": {
        "admin": "Admin scope",
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "OauthSecurity": [
        "user"
      ]
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Description for API Server",
    "title": "IT-Stone Server",
    "version": "0.0.2"
  },
  "basePath": "/api",
  "paths": {
    "/v0/auth/callback": {
      "get": {
        "security": [],
        "summary": "Return access_token and user",
        "operationId": "callback",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "$ref": "#/definitions/UserToken"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/cards": {
      "get": {
        "tags": [
          "card"
        ],
        "summary": "Receiving all cards",
        "operationId": "getCards",
        "responses": {
          "200": {
            "description": "Cards array",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Card"
              }
            }
          },
          "default": {
            "description": "generic Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "card"
        ],
        "summary": "Create a new card",
        "operationId": "createCard",
        "parameters": [
          {
            "name": "card",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/CreatedEntity"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/cards/{id}": {
      "get": {
        "tags": [
          "card"
        ],
        "summary": "Receiving one card by ID",
        "operationId": "getCard",
        "responses": {
          "200": {
            "description": "Return a card with the specified ID",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          },
          "404": {
            "description": "The card with the specified ID was not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "generic Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "card"
        ],
        "summary": "Update one card by ID",
        "operationId": "updateCard",
        "parameters": [
          {
            "name": "card",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The card has been updated",
            "schema": {
              "$ref": "#/definitions/Card"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "card"
        ],
        "summary": "Delete one card by ID",
        "operationId": "deleteCard",
        "responses": {
          "204": {
            "description": "The card has been deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/v0/login": {
      "get": {
        "security": [],
        "tags": [
          "login"
        ],
        "summary": "Login by using Google client OAuth 2.0.",
        "operationId": "login",
        "responses": {
          "200": {
            "description": "Login successful.",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/users": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Receiving all users",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "Receiving all users",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "default": {
            "description": "generic Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v0/users/{id}": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Receiving the user by ID",
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "404": {
            "description": "The user not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Update the user by ID",
        "operationId": "updateUser",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update success",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "404": {
            "description": "The user not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Delete the user by ID",
        "operationId": "deleteUser",
        "responses": {
          "200": {
            "description": "Delete success"
          },
          "404": {
            "description": "The user not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Card": {
      "type": "object",
      "properties": {
        "class": {
          "type": "string"
        },
        "damage": {
          "type": "number"
        },
        "effects": {
          "type": "object"
        },
        "hp": {
          "type": "number"
        },
        "id": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "mana_cost": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "surname": {
          "type": "string"
        }
      }
    },
    "CreatedEntity": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "description": "The email of the User.",
          "type": "string"
        },
        "firstName": {
          "description": "First name of the User.",
          "type": "string"
        },
        "lastName": {
          "description": "Last name of the User.",
          "type": "string"
        },
        "totalGames": {
          "description": "Count of all games of the User.",
          "type": "integer"
        },
        "userID": {
          "description": "The ID of the User.",
          "type": "string"
        },
        "userName": {
          "description": "The user name.",
          "type": "string"
        },
        "winGames": {
          "description": "Count of all games where the User has won.",
          "type": "integer"
        }
      }
    },
    "UserToken": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    }
  },
  "securityDefinitions": {
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
      "scopes": {
        "admin": "Admin scope",
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "OauthSecurity": [
        "user"
      ]
    }
  ]
}`))
}
