apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-19T13:13:50Z"
  labels:
    app: it-stone-server
  name: it-stone-server
  namespace: default
  resourceVersion: "12255"
  selfLink: /api/v1/namespaces/default/services/it-stone-server
  uid: 52052a4c-dadf-11e9-80da-42010a8400bb
spec:
  clusterIP: 10.0.3.2
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31357
      port: 80
      protocol: TCP
      targetPort: 8090
  selector:
    app: it-stone-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.77.12.139