// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "it-stone-server/models"
)

// GetV0AuthCallbackOKCode is the HTTP code returned for type GetV0AuthCallbackOK
const GetV0AuthCallbackOKCode int = 200

/*GetV0AuthCallbackOK login

swagger:response getV0AuthCallbackOK
*/
type GetV0AuthCallbackOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserToken `json:"body,omitempty"`
}

// NewGetV0AuthCallbackOK creates GetV0AuthCallbackOK with default headers values
func NewGetV0AuthCallbackOK() *GetV0AuthCallbackOK {

	return &GetV0AuthCallbackOK{}
}

// WithPayload adds the payload to the get v0 auth callback o k response
func (o *GetV0AuthCallbackOK) WithPayload(payload *models.UserToken) *GetV0AuthCallbackOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v0 auth callback o k response
func (o *GetV0AuthCallbackOK) SetPayload(payload *models.UserToken) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV0AuthCallbackOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetV0AuthCallbackDefault error

swagger:response getV0AuthCallbackDefault
*/
type GetV0AuthCallbackDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV0AuthCallbackDefault creates GetV0AuthCallbackDefault with default headers values
func NewGetV0AuthCallbackDefault(code int) *GetV0AuthCallbackDefault {
	if code <= 0 {
		code = 500
	}

	return &GetV0AuthCallbackDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get v0 auth callback default response
func (o *GetV0AuthCallbackDefault) WithStatusCode(code int) *GetV0AuthCallbackDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get v0 auth callback default response
func (o *GetV0AuthCallbackDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get v0 auth callback default response
func (o *GetV0AuthCallbackDefault) WithPayload(payload *models.Error) *GetV0AuthCallbackDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v0 auth callback default response
func (o *GetV0AuthCallbackDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV0AuthCallbackDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
