// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "it-stone-server/models"
)

// DeleteV0UsersUserIDOKCode is the HTTP code returned for type DeleteV0UsersUserIDOK
const DeleteV0UsersUserIDOKCode int = 200

/*DeleteV0UsersUserIDOK Delete success

swagger:response deleteV0UsersUserIdOK
*/
type DeleteV0UsersUserIDOK struct {
}

// NewDeleteV0UsersUserIDOK creates DeleteV0UsersUserIDOK with default headers values
func NewDeleteV0UsersUserIDOK() *DeleteV0UsersUserIDOK {

	return &DeleteV0UsersUserIDOK{}
}

// WriteResponse to the client
func (o *DeleteV0UsersUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteV0UsersUserIDNotFoundCode is the HTTP code returned for type DeleteV0UsersUserIDNotFound
const DeleteV0UsersUserIDNotFoundCode int = 404

/*DeleteV0UsersUserIDNotFound The user not found.

swagger:response deleteV0UsersUserIdNotFound
*/
type DeleteV0UsersUserIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteV0UsersUserIDNotFound creates DeleteV0UsersUserIDNotFound with default headers values
func NewDeleteV0UsersUserIDNotFound() *DeleteV0UsersUserIDNotFound {

	return &DeleteV0UsersUserIDNotFound{}
}

// WithPayload adds the payload to the delete v0 users user Id not found response
func (o *DeleteV0UsersUserIDNotFound) WithPayload(payload *models.Error) *DeleteV0UsersUserIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v0 users user Id not found response
func (o *DeleteV0UsersUserIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV0UsersUserIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteV0UsersUserIDDefault Unexpected error.

swagger:response deleteV0UsersUserIdDefault
*/
type DeleteV0UsersUserIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteV0UsersUserIDDefault creates DeleteV0UsersUserIDDefault with default headers values
func NewDeleteV0UsersUserIDDefault(code int) *DeleteV0UsersUserIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteV0UsersUserIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete v0 users user ID default response
func (o *DeleteV0UsersUserIDDefault) WithStatusCode(code int) *DeleteV0UsersUserIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete v0 users user ID default response
func (o *DeleteV0UsersUserIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete v0 users user ID default response
func (o *DeleteV0UsersUserIDDefault) WithPayload(payload *models.Error) *DeleteV0UsersUserIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v0 users user ID default response
func (o *DeleteV0UsersUserIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV0UsersUserIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
