// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "it-stone-server/models"
)

// DeleteV0UsersUserIDHandlerFunc turns a function with the right signature into a delete v0 users user ID handler
type DeleteV0UsersUserIDHandlerFunc func(DeleteV0UsersUserIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteV0UsersUserIDHandlerFunc) Handle(params DeleteV0UsersUserIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteV0UsersUserIDHandler interface for that can handle valid delete v0 users user ID params
type DeleteV0UsersUserIDHandler interface {
	Handle(DeleteV0UsersUserIDParams, *models.Principal) middleware.Responder
}

// NewDeleteV0UsersUserID creates a new http.Handler for the delete v0 users user ID operation
func NewDeleteV0UsersUserID(ctx *middleware.Context, handler DeleteV0UsersUserIDHandler) *DeleteV0UsersUserID {
	return &DeleteV0UsersUserID{Context: ctx, Handler: handler}
}

/*DeleteV0UsersUserID swagger:route DELETE /v0/users/{userID} User deleteV0UsersUserId

Delete user by ID.

*/
type DeleteV0UsersUserID struct {
	Context *middleware.Context
	Handler DeleteV0UsersUserIDHandler
}

func (o *DeleteV0UsersUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteV0UsersUserIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
