// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "it-stone-server/models"
)

// GetV0UsersUserIDHandlerFunc turns a function with the right signature into a get v0 users user ID handler
type GetV0UsersUserIDHandlerFunc func(GetV0UsersUserIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV0UsersUserIDHandlerFunc) Handle(params GetV0UsersUserIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetV0UsersUserIDHandler interface for that can handle valid get v0 users user ID params
type GetV0UsersUserIDHandler interface {
	Handle(GetV0UsersUserIDParams, *models.Principal) middleware.Responder
}

// NewGetV0UsersUserID creates a new http.Handler for the get v0 users user ID operation
func NewGetV0UsersUserID(ctx *middleware.Context, handler GetV0UsersUserIDHandler) *GetV0UsersUserID {
	return &GetV0UsersUserID{Context: ctx, Handler: handler}
}

/*GetV0UsersUserID swagger:route GET /v0/users/{userID} User getV0UsersUserId

Find user by ID.

*/
type GetV0UsersUserID struct {
	Context *middleware.Context
	Handler GetV0UsersUserIDHandler
}

func (o *GetV0UsersUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV0UsersUserIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
