// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetV0LoginParams creates a new GetV0LoginParams object
// no default values defined in spec.
func NewGetV0LoginParams() GetV0LoginParams {

	return GetV0LoginParams{}
}

// GetV0LoginParams contains all the bound params for the get v0 login operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetV0Login
type GetV0LoginParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetV0LoginParams() beforehand.
func (o *GetV0LoginParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
