// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "it-stone-server/models"
)

// GetV0LoginOKCode is the HTTP code returned for type GetV0LoginOK
const GetV0LoginOKCode int = 200

/*GetV0LoginOK Login successful.

swagger:response getV0LoginOK
*/
type GetV0LoginOK struct {

	/*
	  In: Body
	*/
	Payload *GetV0LoginOKBody `json:"body,omitempty"`
}

// NewGetV0LoginOK creates GetV0LoginOK with default headers values
func NewGetV0LoginOK() *GetV0LoginOK {

	return &GetV0LoginOK{}
}

// WithPayload adds the payload to the get v0 login o k response
func (o *GetV0LoginOK) WithPayload(payload *GetV0LoginOKBody) *GetV0LoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v0 login o k response
func (o *GetV0LoginOK) SetPayload(payload *GetV0LoginOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV0LoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetV0LoginDefault error

swagger:response getV0LoginDefault
*/
type GetV0LoginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV0LoginDefault creates GetV0LoginDefault with default headers values
func NewGetV0LoginDefault(code int) *GetV0LoginDefault {
	if code <= 0 {
		code = 500
	}

	return &GetV0LoginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get v0 login default response
func (o *GetV0LoginDefault) WithStatusCode(code int) *GetV0LoginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get v0 login default response
func (o *GetV0LoginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get v0 login default response
func (o *GetV0LoginDefault) WithPayload(payload *models.Error) *GetV0LoginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v0 login default response
func (o *GetV0LoginDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV0LoginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
