// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "it-stone-server/models"
)

// GetUserByTokenHandlerFunc turns a function with the right signature into a get user by token handler
type GetUserByTokenHandlerFunc func(GetUserByTokenParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserByTokenHandlerFunc) Handle(params GetUserByTokenParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetUserByTokenHandler interface for that can handle valid get user by token params
type GetUserByTokenHandler interface {
	Handle(GetUserByTokenParams, *models.Principal) middleware.Responder
}

// NewGetUserByToken creates a new http.Handler for the get user by token operation
func NewGetUserByToken(ctx *middleware.Context, handler GetUserByTokenHandler) *GetUserByToken {
	return &GetUserByToken{Context: ctx, Handler: handler}
}

/*GetUserByToken swagger:route GET /v0/user user getUserByToken

Receiving the user by token

*/
type GetUserByToken struct {
	Context *middleware.Context
	Handler GetUserByTokenHandler
}

func (o *GetUserByToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserByTokenParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
