// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "it-stone-server/models"
)

// PutV0UsersUserIDOKCode is the HTTP code returned for type PutV0UsersUserIDOK
const PutV0UsersUserIDOKCode int = 200

/*PutV0UsersUserIDOK Update success

swagger:response putV0UsersUserIdOK
*/
type PutV0UsersUserIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPutV0UsersUserIDOK creates PutV0UsersUserIDOK with default headers values
func NewPutV0UsersUserIDOK() *PutV0UsersUserIDOK {

	return &PutV0UsersUserIDOK{}
}

// WithPayload adds the payload to the put v0 users user Id o k response
func (o *PutV0UsersUserIDOK) WithPayload(payload *models.User) *PutV0UsersUserIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put v0 users user Id o k response
func (o *PutV0UsersUserIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutV0UsersUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutV0UsersUserIDNotFoundCode is the HTTP code returned for type PutV0UsersUserIDNotFound
const PutV0UsersUserIDNotFoundCode int = 404

/*PutV0UsersUserIDNotFound The user not found.

swagger:response putV0UsersUserIdNotFound
*/
type PutV0UsersUserIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutV0UsersUserIDNotFound creates PutV0UsersUserIDNotFound with default headers values
func NewPutV0UsersUserIDNotFound() *PutV0UsersUserIDNotFound {

	return &PutV0UsersUserIDNotFound{}
}

// WithPayload adds the payload to the put v0 users user Id not found response
func (o *PutV0UsersUserIDNotFound) WithPayload(payload *models.Error) *PutV0UsersUserIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put v0 users user Id not found response
func (o *PutV0UsersUserIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutV0UsersUserIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutV0UsersUserIDDefault Unexpected error.

swagger:response putV0UsersUserIdDefault
*/
type PutV0UsersUserIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutV0UsersUserIDDefault creates PutV0UsersUserIDDefault with default headers values
func NewPutV0UsersUserIDDefault(code int) *PutV0UsersUserIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PutV0UsersUserIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put v0 users user ID default response
func (o *PutV0UsersUserIDDefault) WithStatusCode(code int) *PutV0UsersUserIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put v0 users user ID default response
func (o *PutV0UsersUserIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put v0 users user ID default response
func (o *PutV0UsersUserIDDefault) WithPayload(payload *models.Error) *PutV0UsersUserIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put v0 users user ID default response
func (o *PutV0UsersUserIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutV0UsersUserIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
