// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "it-stone-server/models"
)

// PutV0UsersUserIDHandlerFunc turns a function with the right signature into a put v0 users user ID handler
type PutV0UsersUserIDHandlerFunc func(PutV0UsersUserIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutV0UsersUserIDHandlerFunc) Handle(params PutV0UsersUserIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutV0UsersUserIDHandler interface for that can handle valid put v0 users user ID params
type PutV0UsersUserIDHandler interface {
	Handle(PutV0UsersUserIDParams, *models.Principal) middleware.Responder
}

// NewPutV0UsersUserID creates a new http.Handler for the put v0 users user ID operation
func NewPutV0UsersUserID(ctx *middleware.Context, handler PutV0UsersUserIDHandler) *PutV0UsersUserID {
	return &PutV0UsersUserID{Context: ctx, Handler: handler}
}

/*PutV0UsersUserID swagger:route PUT /v0/users/{userID} User putV0UsersUserId

Update user info by ID.

*/
type PutV0UsersUserID struct {
	Context *middleware.Context
	Handler PutV0UsersUserIDHandler
}

func (o *PutV0UsersUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutV0UsersUserIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
