// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Card card
// swagger:model Card
type Card struct {

	// class
	Class string `json:"class,omitempty"`

	// damage
	Damage float64 `json:"damage,omitempty"`

	// effects
	Effects interface{} `json:"effects,omitempty"`

	// hp
	Hp float64 `json:"hp,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// mana cost
	ManaCost float64 `json:"mana_cost,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// skills
	Skills []string `json:"skills"`

	// surname
	Surname string `json:"surname,omitempty"`
}

// Validate validates this card
func (m *Card) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Card) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Card) UnmarshalBinary(b []byte) error {
	var res Card
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
