// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RegistrationForm registration form
// swagger:model RegistrationForm
type RegistrationForm struct {

	// email
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email"`

	// password
	// Required: true
	Password *string `json:"password"`

	// user name
	// Required: true
	// Max Length: 16
	// Min Length: 3
	// Pattern: ^[A-Za-z0-9_]{3,16}$
	UserName *string `json:"userName"`
}

// Validate validates this registration form
func (m *RegistrationForm) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegistrationForm) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RegistrationForm) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *RegistrationForm) validateUserName(formats strfmt.Registry) error {

	if err := validate.Required("userName", "body", m.UserName); err != nil {
		return err
	}

	if err := validate.MinLength("userName", "body", string(*m.UserName), 3); err != nil {
		return err
	}

	if err := validate.MaxLength("userName", "body", string(*m.UserName), 16); err != nil {
		return err
	}

	if err := validate.Pattern("userName", "body", string(*m.UserName), `^[A-Za-z0-9_]{3,16}$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RegistrationForm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistrationForm) UnmarshalBinary(b []byte) error {
	var res RegistrationForm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
