// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// User user
// swagger:model User
type User struct {

	// The email of the User.
	Email string `json:"email,omitempty"`

	// First name of the User.
	FirstName string `json:"firstName,omitempty"`

	// Last name of the User.
	LastName string `json:"lastName,omitempty"`

	// Count of all games of the User.
	TotalGames int64 `json:"totalGames,omitempty"`

	// The ID of the User.
	UserID string `json:"userID,omitempty"`

	// The user name.
	UserName string `json:"userName,omitempty"`

	// Count of all games where the User has won.
	WinGames int64 `json:"winGames,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
